# NumPy
## Resources
* [NumPy Manual](https://docs.scipy.org/doc/numpy/index.html)
* [User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

In [6]:
import numpy as np
numpy.version.version

'1.15.0'

## What are arrays?
NumPy's main object is the multi-dimensional array. It's like a Python list but everything inside it must be the same datatype. Basically, this allows you to make matrices.

Numpy arrays are in Python. Everything in Python is an object. Objects have attributes. Therefore, numpy arrays have attritubes.

Numpy arrays differ from Python arrays, so don't confuse the two. Numpy arrays are optimized for processing speed.

NumPy's array class is called `ndarray`. The most important are:
* `ndaaray.ndim`: return the number of axes (or dimensions of the array (int)
* `ndarray.shape`: return the dimensions of the array (tuple) in the form (n_rows, m_columns), the length of the tuple is the number of axes
* `ndarray.size`: return the total number of elements of the array (int)
* `ndarray.dtype`: return the datatype of the elements of the array
* `ndaarray.itemsize`: return the byte size of each element of the array

In [12]:
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
type(x)

numpy.ndarray

In [15]:
x.ndim

2

In [16]:
x.shape

(3, 5)

In [17]:
x.size

15

In [18]:
x.dtype

dtype('int32')

In [20]:
x.itemsize

4

In [21]:
x.dtype.name

'int32'

## How do you create arrays?
There are several ways to create arrays.
1. Create from a Python list or tuple using `np.array`
2. Create from with placeholder values with `np.zeros` or `np.ones`
3. Create from sequence of numbers with `np.arange`

In [24]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [25]:
b = np.array([(1,2,3), (4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
c = np.array([1,2,3], dtype=float)
c

array([1., 2., 3.])

In [27]:
d = np.zeros((2,5))
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
e = np.ones((3,2), dtype=int)
e

array([[1, 1],
       [1, 1],
       [1, 1]])

In [37]:
f = np.arange(10, 21, 2)
f

array([10, 12, 14, 16, 18, 20])

## How do you print and interpret arrays?

They look like nested lists in base Python with the following layout:
* the last axis is printed left to right
* the second-to-last axis is printed top to bottom
* the remainder are printed top to bottom with each slice separated by an empty line

One-dimensional arrays look like rows. Two-dimensional arrays look like matrices. Three-dimensional arrays look like lists of matrices. If an array is too large to print, then ellipses are used to represent the intermediate values, but this can be disabled.

In [44]:
a = np.arange(5)
b = np.arange(12).reshape(4,3)
c = np.arange(24).reshape(2,3,4)
print("1D:\n", a)
print("\n2D:\n", b)
print("\n3D:\n", c)

1D:
 [0 1 2 3 4]

2D:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

3D:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [46]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [47]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


## What can you do with arrays?

* basic operations, which operate element-wise
* [universal functions](https://docs.scipy.org/doc/numpy/user/quickstart.html#universal-functions)
* basic statistics, linear algebra, sorting, and [more](https://docs.scipy.org/doc/numpy/user/quickstart.html#functions-and-methods-overview)

In [48]:
a = np.arange(20,51,10)
a

array([20, 30, 40, 50])

In [51]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [53]:
a - b

array([19, 28, 37, 46])

In [54]:
b**2

array([ 1,  4,  9, 16], dtype=int32)

In [56]:
a <= 30

array([ True,  True, False, False])

In [60]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [65]:
C = np.array( [[2,2],
               [0,1]] )
D = np.array( [[2,0],
               [3,4]] )
print("Element-wise product:\n", C*D)
print("\nMatrix product:\n", C@D)
print("\nEquivalent matrix product:\n", C.dot(D))

Element-wise product:
 [[4 0]
 [0 4]]

Matrix product:
 [[10  8]
 [ 3  4]]

Equivalent matrix product:
 [[10  8]
 [ 3  4]]


In [66]:
a.mean()

35.0